### PR TITLE
first pass at PBCore documentation

### PR DESCRIPTION
**Pull request by jerielizabeth**
Documentation for the new PBCore plugin. Explaining the nested elements was a bit tricky, so that in particular deserves additional eyes. 

Will need to update if current issues on plugin result in functionality changes.

### CODE REVIEW

**Comment by mebrett** [comment]
Line 17 (Adding an Item): You say "Each PB Core element has a description (from the standard) and an input field." You might be more clear that the description is of the element and displays above the input field.

Line 29 (Adding Item File Metadata): the word metadata is missing an 'a'

In the final image, you might also add arrows for the delete buttons to uninstall the element sets.

Otherwise, looks good.

**Comment by jerielizabeth** [comment]
Changes made! I will keep thinking about the line 17 change - I made a few minor changes but I think it could be clearer.

**Comment by sharonmleon** [comment]
@jerielizabeth @mebrett I added some stuff about the instantiation metadata and another screenshot that is from the sitewide appearance settings. Not sure if any of that is clear, so I'd appreciate eyes on.

**Comment by mebrett** [comment]
I know there are a lot of images already, but I would recommend breaking out the information about title duplication and hide elements into it own subsection, with at least an image to show the double Title on the public view if HideElements is /not/ in use.

**Comment by jerielizabeth** [comment]
I agree on the hide elements bit needing some screen shots. I'll take a quick pass at that.

**Comment by jerielizabeth** [comment]
I impulsively changed the image for the link file to metadata bit and then realized that it's gone through a number of iterations already. Just thought this image was a bit clearer but happy to revert back.

**Comment by sharonmleon** [comment]
No, that's definitely better. 

Also, John thought that it might be useful to also have a picture of the files sidebar on the admin item show. Since everything matches at this point, would you grab that one too, @jerielizabeth?

**Comment by jerielizabeth** [comment]
I think that completes the outstanding to-dos for the PB Core plugin docs on my end.

**Comment by sharonmleon** [comment]
And with that, I think we're done. 

@mebrett Would you like to do the merge?

**Pull request merged**
